# docker-compose.yml
version: '3.3'

services:
  websocket:
    build:
      context: .
      dockerfile: websocket_service/Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  analyzer:
    build:
      context: .
      dockerfile: ai_service/Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge